os: osx
osx_image: xcode61
language: objective-c
script:
- make bin/bossac
- mkdir deploy
- cp bin/bossac deploy
deploy:
  provider: s3
  access_key_id: AKIAIHMTFTT3MKICVLSQ
  secret_access_key:
    secure: nCng/hGBHJ+yNufj0GQ+gg79k6p9RzEqJ0KqRIXkhhWlIbxvND8hVVqcLStbIxOS7tiYAefwmgorIlueaZGyJRpF6W3OcS2TW28zGMLSsc5omyC6UZYgHknoajkfxkly8eO85w5elDeU/vvg6xqMhe6al9Uk0B6LVr/IG2CdA9I=
  bucket: bossaosx
  skip_cleanup: true
  local_dir: deploy
  acl: public_read
  on:
    repo: itdaniher/BOSSA
    all_branches: true
