os: osx
osx_image: xcode61
language: objective-c
script:
- make bin/bossac
- mkdir deploy
- cp bin/bossac deploy
deploy:
  provider: s3
  access_key_id: AKIAJIUMJWTHBLSLXXPA
  secret_access_key:
    secure: fAnkY7ZrbN1JzCY2vJ2VNfuG6ipIEPufcV0fL54bKz3AgiywtMfCDbhb+CUZVqCMMlsqZaO/rggz3/ODEQwz2WFJ4jlNqtP5o24NwIFKLWe3wq4DOU0tfQgsC4E+HsnrholsLTIWA5nKgLF6KtLNwPguq+fytvmWqv3nRxRk6I0=
  bucket: bossaosx
  skip_cleanup: true
  local_dir: deploy
  acl: public_read
  on:
    repo: itdaniher/BOSSA
    all_branches: true
